[package]
name = "compiler"
version = "0.1.0"
edition = "2018"

[dependencies]
rayon = "1.5.1"
wasmer = "2.0"
tokio = { version = "1", features = ["full"] }
async-trait = "0.1.51"

[dev-dependencies]
pretty_assertions = "0.7.2"
